"""
texts.py — Barcha UI tarjimalar (O'zbekcha Kirill va Lotin)
"""

STR: dict[str, dict[str, str]] = {
"cyr": {
    "main_title":    "📦 *НЕРЖАВЕЙКА*\n\nАсосий менюдасиз:",
    "b_order":       "📥 Буюртма йиғиш",
    "b_load":        "🚛 Контейнер юклаш",
    "b_status":      "📈 Ҳолат",
    "b_search":      "🔍 Қидируш",
    "b_settings":    "⚙️ Созламалар",
    "order_title":   "📥 *Буюртма йиғиш*\n\nҚайси канал учун?",
    "ch_asosiy":     "🏢 Асосий (омборлар ва филиаллар)",
    "ch_sex":        "🏭 Цех (ишлаб чиқариш)",
    "ch_osh":        "🇰🇬 Ўш (Қирғизистон)",
    "order_ch_title":"Амални танланг:",
    "b_kamomat":     "📊 Камоматни кўриш",
    "b_excel":       "📄 Буюртма Excel олиш",
    "b_tasdiq":      "✅ Тасдиқланган буюртмани юбориш",
    "kamomat_title": "📊 *{ch}* — камомат:",
    "kamomat_line":  "🔴 Критик: *{kritik}* та\n🟡 Паст: *{past}* та\n✅ Буюртма берилди: {b} та\n⏳ Ҳали берилмади: {p} та",
    "kamomat_yoq":   "✅ Ҳозирча камомат йўқ.",
    "excel_caption": "📄 Камомат рўйхати ({ch}).\n\n☝️ Буюртма устунини тўлдиринг.\nТайёр бўлгач — *Тасдиқланган буюртмани юбориш* тугмасини босинг.",
    "tasdiq_prompt": "✅ *Тасдиқланган буюртма — {ch}*\n\nЎзгартирилган Excel файлни юборинг.\nБот реал буюртма сифатида сақлайди.",
    "tasdiq_ok":     "✅ Буюртма қабул қилинди: {n} та товар.\nКейин камоматда берилмаганлар кўринади.",
    "tasdiq_err":    "❌ *Нотўғри формат*\n\n{xato}\n\nКеракли формат:\n— 6 та варақ: Труба · Профиль · Лист · Баласина · Стойка · Аксессуар\n— Ҳар бирида: №, Товар, Буюртма, Изоҳ",
    "load_title":    "🚛 *Контейнер юклаш*\n\nҚайси канал учун юк тайёрланади?",
    "load_ch_title": "🚛 *{ch}* — Юклаш режаси\n\nХитой тайёр рўйхатини юборинг (.xlsx).\nБир нечта файл юборсангиз ҳаммаси қўшилади.\nТайёр бўлгач — *▶️ Ҳисоблаш* тугмасини босинг.",
    "b_upload":      "📎 Хитой Excelини юклаш",
    "b_hisoblash":   "▶️ Ҳисоблаш",
    "fayl_qoshildi": "✅ *{n} та товар қўшилди.* Жами: *{jami} та*.\n\nЯна файл юборинг ёки *▶️ Ҳисоблаш* тугмасини босинг.",
    "fayl_qoshildi_buyurtma": "✅ *{n} та товар қўшилди.* Жами: *{jami} та*.\n\nЯна файл юборинг ёки *✅ Тайёр* тугмасини босинг.",
    "xitoy_ok":      "📎 Хитой файли қабул қилинди — {n} та товар аниқланди.\n_(Юклаш плани — кейинги босқич)_",
    "xitoy_err":     "❌ Файлни ўқишда хато: {xato}",
    "status_title":  "📈 *Ҳолат*",
    "b_karta":       "🔍 Қидируш",
    "b_yolda":       "🚢 Йўлдаги ҳолат",
    "karta_title":    "📊 *Товар картаси*",
    "karta_kat_sor":  "Категорияни танланг:",
    "grafik_truba":   "🔘 *Труба* — формат:\n`51 -> 0,9 -> 5,8 -> 201`\n\n_диаметр → стенка → узунлик → марка_\n\nЁзинг 👇",
    "grafik_profil":  "🔲 *Профиль* — формат:\n`20 20 0,7 6 201`\n_ёки_ `20х20 0,7 6`\n\n_ўлчам ўлчам стенка узунлик (марка — ихтиёрий)_\n\nЁзинг 👇",
    "grafik_list":    "📄 *Лист* — формат:\n`0,8 1220 201`\n_ёки_ `0,8 1500`\n\n_қалинлик кенглик (марка — ихтиёрий)_\n\nЁзинг 👇",
    "grafik_bal":     "📏 *Баласина* — рақамини ёзинг:\n`01` ёки `02` ...\n\nЁзинг 👇",
    "grafik_stoyka":  "🔩 *Стойка* — рақамини ёзинг:\n`01` ёки `34` ...\n\nЁзинг 👇",
    "grafik_chas":    "🎯 *Чашка* — ўлчамини ёзинг:\n`51` — труба чашкаси\n`40 40` — профил чашкаси\n\nЁзинг 👇",
    "grafik_kuz":     "🍄 *Қузиқорин* — ўлчамини ёзинг:\n`51` ёки `38` ...\n_(тўғри ва қийшиқ — иккаласи чиқади)_\n\nЁзинг 👇",
    "grafik_shar":    "🔵 *Шар* — ўлчамини ёзинг:\n`76` ёки `63` ёки `51` ...\n\nЁзинг 👇",
    "grafik_sokka":   "💿 *Соққа* — ўлчамини ёзинг:\n`90 25` ёки `80 25` ёки `51` ...\n\nЁзинг 👇",
    "grafik_oyna":    "🪟 *Ойна держатель* — рақамини ёзинг:\n`01` ёки `03` ...\n\nЁзинг 👇",
    "grafik_topilmadi": "❌ Товар топилмади.\nФорматга қараб қайта ёзинг.",
    "grafik_tanlang": "📋 *Қайси товар?*\n\nБир нечта натижа — аниғини танланг:",
    "yolda_title":   "🚢 *Йўлдаги контейнерлар ({n} та):*\n\n",
    "yolda_yoq":     "✅ Ҳозирча йўлда контейнер йўқ.",
    "yolda_header":  "Контейнер     | Юкланган   | Келиш      | Қолди",
    "yolda_sep":     "--------------|------------|------------|----------",
    "kech_label":    "{k} кун кеч ⚠️",
    "kun_label":     "{k} кун 🚢",
    "search_title":  "🔍",
    "search_stub":   "🔍 *{q}* — натижалар:\n\n_(ҳозирча скелет — мантиқ кейин уланади)_",
    "settings_title":"⚙️ *Созламалар*",
    "b_lang":        "🌐 Тилни ўзгартириш",
    "b_yangilash":   "🔄 Маълумотларни янгилаш",
    "buyurtma_yoq":  "✅ *Hozircha buyurtma kerak emas.*\n\nBarcha yetishmovchiliklar allaqachon buyurilgan (tasdiqlangan buyurtma hisobga olindi).",
    "yangilash_boshld":"⏳ Янгиланмоқда... (30-60 сония)",
    "yangilash_ok":  "✅ Yangilandi! Power BI ma'lumotlari yangilandi.",
    "yangilash_err": "❌ Yangilashda xato: {xato}",
    "back":          "⬅️ Орқага",
    "data_yoq":      "⚠️ Маълумот топилмади.\nАввал NEJAVIYKA\\_v3.py ни ишга туширинг.",
    "fayl_kutilmadi":"❓ Файл кутилмаган эди. Менюдан амални танланг.",
    "xitoy_sorash":  "❓ *Хитойда остатка махсулотимиз борми ?*\n\n(Тайёр ёки тайёрланаётган — фарқи йўқ)\nХаммаси хиобга олинади.",
    "xitoy_ha":      "✅ Ҳа, бор",
    "xitoy_yoq":     "❌ Йўқ — шундайича бер",
    "xitoy_fayl_kut":"📎 *Хитой остатка файлини юборинг.*\n\n_(Excel .xlsx формат)_",
    "xitoy_fayl_kut_tp":  "📎 *1/2 — Труба/Профиль Хитой файлини юборинг.*\n\n_(Excel .xlsx формат)_",
    "xitoy_fayl_kut_list":"📎 *2/2 — Лист Хитой файлини юборинг.*\n\n_(Excel .xlsx формат)_",
    "xitoy_tp_qabul": "✅ Труба/Профиль қабул қилинди: *{n}* та товар.",
    "xitoy_qabul":   "✅ Хитой остатка қабул қилинди: *{n}* та товар.\nБуюртма Excel тайёрланмоқда...",
    "xitoy_ishlatsin":"✅ Мавжудни ишлатсин",
    "xitoy_yangi":   "🔄 Янги юклаш",
    "xitoy_hisob_siz":"❌ Ҳисобсиз бер",
    "xitoy_mavjud":  "🇨🇳 *Хитой остатка мавжуд*\n\n📦 {ch}: *{n}* та товар\n🕐 Юкланган: *{sana}*\n\nНима қилайлик?",
    "b_tozala_buy":  "🗑 Буюртмани тозалаш",
    "b_tozala_xitoy":"🇨🇳 Хитой остаткани тозалаш",
    "tozala_sor_buy":"🗑 Қайси канал буюртмасини тозалайман?",
    "tozala_sor_xitoy":"🇨🇳 Қайси канал хитой остаткасини тозалайман?",
    "tozala_tasdiq_buy":"🗑 *{ch}* буюртмаси: *{n}* та товар ({sana}).\nҲақиқатан тозалайсизми?",
    "tozala_tasdiq_xitoy":"🇨🇳 *{ch}* хитой остатка: *{n}* та товар ({sana}).\nҲақиқатан тозалайсизми?",
    "tozala_topilmadi":"ℹ️ *{ch}* да тозалайдиган нарса топилмади.",
    "tozala_ok":     "✅ *{ch}* — тозаланди.",
    "tozala_ha":     "✅ Ҳа, тозала",
    "tozala_bekor":  "❌ Бекор қилинди.",
    "zakaz_preview": "📋 *Тасдиқлаш — {ch}*\n\nЖами *{n}* та товар:{tafsilot}\n\nТасдиқлайсизми?",
    "zakaz_tasdiq_btn":"✅ Тасдиқлаш",
    "zakaz_bekor_btn":"❌ Бекор қилиш",
    "zakaz_bekor_msg":"❌ Закоз бекор қилинди.",
    "xitoy_qabul_yana":"✅ *{n}* та товар қабул қилинди.\n🇨🇳 Жами омборда: *{jami}* та\n\nЯна файл борми?",
    "xitoy_yana_btn":  "➕ Яна файл",
    "xitoy_tayyor_btn":"✅ Тайёр — Excel яратиш",
    "kritik_stub":   "📊 Критик товарлар рўйхати тайёрланмоқда...",
    # Yo'lga konteyner qo'shish
    "b_yolga_kont":    "🚢 Йўлга контейнер қўшиш",
    "kont_tp_kut":     "📎 *1/2 — Труба/Профиль装箱单 файлини юборинг.*\n\n_(Excel .xlsx формат)_",
    "kont_list_kut":   "📎 *2/2 — Лист出货清单 файлини юборинг.*\n\n_(Excel .xls/.xlsx формат)_",
    "kont_tasdiq_ha":  "✅ Ҳа, қўшиш",
    "kont_tasdiq_yoq": "❌ Бекор",
    "kont_qoshildi":   "✅ *{n}* та контейнер йўлда рўйхатига қўшилди!",
    "kont_xato":       "❌ Файл ўқишда хато: {xato}",
    "kont_barchasi_bor":"✅ Барча контейнерлар аллақачон рўйхатда.",
    # Filyal (user) interfeysi
    "user_main_title":  "📦 *НЕРЖАВЕЙКА*\n\nНима қилайлик?",
    "b_yolda_excel":    "🚢 Йўлдаги ҳолат",
    "settings_title_user": "⚙️ *Созламалар*",
    "b_boglanish":      "📞 Админ билан боғланиш",
    "boglanish_phone":  "📞 Қўнғироқ қилиш",
    "boglanish_tg":     "💬 Телеграмдан боғланиш",
    "yolda_excel_yoq":  "ℹ️ Ҳозирча йўлда контейнер йўқ.",
},
"lat": {
    "main_title":    "📦 *NERJAVEYKA*\n\nAsosiy menyudasiz:",
    "b_order":       "📥 Buyurtma yig'ish",
    "b_load":        "🚛 Konteyner yuklash",
    "b_status":      "📈 Holat",
    "b_search":      "🔍 Qidiruv",
    "b_settings":    "⚙️ Sozlamalar",
    "order_title":   "📥 *Buyurtma yig'ish*\n\nQaysi kanal uchun?",
    "ch_asosiy":     "🏢 Asosiy (omborlar va filiallar)",
    "ch_sex":        "🏭 Tsex (ishlab chiqarish)",
    "ch_osh":        "🇰🇬 O'sh (Qirg'iziston)",
    "order_ch_title":"Amalni tanlang:",
    "b_kamomat":     "📊 Kamomatni ko'rish",
    "b_excel":       "📄 Buyurtma Excel olish",
    "b_tasdiq":      "✅ Tasdiqlangan buyurtmani yuborish",
    "kamomat_title": "📊 *{ch}* — kamomat:",
    "kamomat_line":  "🔴 Kritik: *{kritik}* ta\n🟡 Past: *{past}* ta\n✅ Buyurtma berildi: {b} ta\n⏳ Hali berilmadi: {p} ta",
    "kamomat_yoq":   "✅ Hozircha kamomat yo'q.",
    "excel_caption": "📄 Kamomat ro'yxati ({ch}).\n\n☝️ Buyurtma ustunini to'ldiring.\nTayyor bo'lgach — *Tasdiqlangan buyurtmani yuborish* tugmasini bosing.",
    "tasdiq_prompt": "✅ *Tasdiqlangan buyurtma — {ch}*\n\nO'zgartirilgan Excel faylni yuboring.\nBot real buyurtma sifatida saqlaydi.",
    "tasdiq_ok":     "✅ Buyurtma qabul qilindi: {n} ta tovar.\nKeyingi kamomatda berilmaganlar ko'rinadi.",
    "tasdiq_err":    "❌ *Noto'g'ri format*\n\n{xato}\n\nKerakli format:\n— 6 ta varaq: Труба · Профиль · Лист · Баласина · Стойка · Аксессуар\n— Har birida: №, Товар, Буюртма, Изоҳ",
    "load_title":    "🚛 *Konteyner yuklash*\n\nQaysi kanal uchun yuk tayyorlanadi?",
    "load_ch_title": "🚛 *{ch}* — Yuklash rejasi\n\nXitoy tayyor ro'yxatini yuboring (.xlsx).\nBir nechta fayl yuborsangiz hammasi qo'shiladi.\nTayyor bo'lgach — *▶️ Hisoblash* tugmasini bosing.",
    "b_upload":      "📎 Xitoy Excelini yuklash",
    "b_hisoblash":   "▶️ Hisoblash",
    "fayl_qoshildi": "✅ *{n} ta tovar qo'shildi.* Jami: *{jami} ta*.\n\nYana fayl yuboring yoki *▶️ Hisoblash* tugmasini bosing.",
    "fayl_qoshildi_buyurtma": "✅ *{n} ta tovar qo'shildi.* Jami: *{jami} ta*.\n\nYana fayl yuboring yoki *✅ Tayyor* tugmasini bosing.",
    "xitoy_ok":      "📎 Xitoy fayli qabul qilindi — {n} ta tovar aniqlandi.\n_(Yuklash plani — keyingi bosqich)_",
    "xitoy_err":     "❌ Faylni o'qishda xato: {xato}",
    "status_title":  "📈 *Holat*",
    "b_karta":       "🔍 Qidiruv",
    "b_yolda":       "🚢 Yo'ldagi holat",
    "karta_title":    "📊 *Tovar kartasi*",
    "karta_kat_sor":  "Kategoriyani tanlang:",
    "grafik_truba":   "🔘 *Труба* — format:\n`51 -> 0,9 -> 5,8 -> 201`\n\n_diametr → stenka → uzunlik → marka_\n\nYozing 👇",
    "grafik_profil":  "🔲 *Профиль* — format:\n`20 20 0,7 6 201`\n_yoki_ `20х20 0,7 6`\n\n_o'lcham o'lcham stenka uzunlik (marka — ixtiyoriy)_\n\nYozing 👇",
    "grafik_list":    "📄 *Лист* — format:\n`0,8 1220 201`\n_yoki_ `0,8 1500`\n\n_qalinlik kenglik (marka — ixtiyoriy)_\n\nYozing 👇",
    "grafik_bal":     "📏 *Баласина* — raqamini yozing:\n`01` yoki `02` ...\n\nYozing 👇",
    "grafik_stoyka":  "🔩 *Стойка* — raqamini yozing:\n`01` yoki `34` ...\n\nYozing 👇",
    "grafik_chas":    "🎯 *Чашка* — o'lchamini yozing:\n`51` — truba chashkasi\n`40 40` — profil chashkasi\n\nYozing 👇",
    "grafik_kuz":     "🍄 *Қузиқорин* — o'lchamini yozing:\n`51` yoki `38` ...\n_(to'g'ri va qiyshiq — ikkalasi chiqadi)_\n\nYozing 👇",
    "grafik_shar":    "🔵 *Шар* — o'lchamini yozing:\n`76` yoki `63` yoki `51` ...\n\nYozing 👇",
    "grafik_sokka":   "💿 *Соққа* — o'lchamini yozing:\n`90 25` yoki `80 25` yoki `51` ...\n\nYozing 👇",
    "grafik_oyna":    "🪟 *Ойна держатель* — raqamini yozing:\n`01` yoki `03` ...\n\nYozing 👇",
    "grafik_topilmadi": "❌ Tovar topilmadi.\nFormatga qarab qayta yozing.",
    "grafik_tanlang": "📋 *Qaysi tovar?*\n\nBir nechta natija — aniqini tanlang:",
    "yolda_title":   "🚢 *Yo'ldagi konteynerlar ({n} ta):*\n\n",
    "yolda_yoq":     "✅ Hozircha yo'lda konteyner yo'q.",
    "yolda_header":  "Konteyner     | Yuklangan  | Kelish     | Qoldi",
    "yolda_sep":     "--------------|------------|------------|----------",
    "kech_label":    "{k} kun kech ⚠️",
    "kun_label":     "{k} kun 🚢",
    "search_title":  "🔍",
    "search_stub":   "🔍 *{q}* — natijalar:\n\n_(hozircha skelet — mantiq keyin ulanadi)_",
    "settings_title":"⚙️ *Sozlamalar*",
    "b_lang":        "🌐 Tilni o'zgartirish",
    "b_yangilash":   "🔄 Ma'lumotlarni yangilash",
    "buyurtma_yoq":  "✅ *Hozircha buyurtma kerak emas.*\n\nBarcha yetishmovchiliklar allaqachon buyurilgan (tasdiqlangan buyurtma hisobga olindi).",
    "yangilash_boshld":"⏳ Yangilanmoqda... (30-60 soniya)",
    "yangilash_ok":  "✅ Yangilandi! Power BI ma'lumotlari yangilandi.",
    "yangilash_err": "❌ Yangilashda xato: {xato}",
    "back":          "⬅️ Orqaga",
    "data_yoq":      "⚠️ Ma'lumot topilmadi.\nAvval NEJAVIYKA\\_v3.py ni ishga tushiring.",
    "fayl_kutilmadi":"❓ Fayl kutilmagan edi. Menyudan amalni tanlang.",
    "xitoy_sorash":  "❓ *Xitoyda ostatka mahsulotmiz bormi?*\n\n(Tayyor yoki tayyorlanayotgan — farqi yo'q)\nBarchasi hisobga olinadi.",
    "xitoy_ha":      "✅ Ha, bor",
    "xitoy_yoq":     "❌ Yo'q — shundayicha ber",
    "xitoy_fayl_kut":"📎 *Xitoy ostatka faylini yuboring.*\n\n_(Excel .xlsx format)_",
    "xitoy_fayl_kut_tp":  "📎 *1/2 — Truба/Profil Xitoy faylini yuboring.*\n\n_(Excel .xlsx format)_",
    "xitoy_fayl_kut_list":"📎 *2/2 — List Xitoy faylini yuboring.*\n\n_(Excel .xlsx format)_",
    "xitoy_tp_qabul": "✅ Truба/Profil qabul qilindi: *{n}* ta tovar.",
    "xitoy_qabul":   "✅ Qabul qilindi: *{n}* ta tovar.\nBuyurtma Excel tayyorlanmoqda...",
    "xitoy_ishlatsin":"✅ Mavjudni ishlatsin",
    "xitoy_yangi":   "🔄 Yangi yuklash",
    "xitoy_hisob_siz":"❌ Hisobsiz ber",
    "xitoy_mavjud":  "🇨🇳 *Xitoy ostatka mavjud*\n\n📦 {ch}: *{n}* ta tovar\n🕐 Yuklangan: *{sana}*\n\nNima qilaylik?",
    "b_tozala_buy":  "🗑 Buyurtmani tozalash",
    "b_tozala_xitoy":"🇨🇳 Xitoy ostatkani tozalash",
    "tozala_sor_buy":"🗑 Qaysi kanal buyurtmasini tozalay?",
    "tozala_sor_xitoy":"🇨🇳 Qaysi kanal xitoy ostatkasini tozalay?",
    "tozala_tasdiq_buy":"🗑 *{ch}* buyurtmasi: *{n}* ta tovar ({sana}).\nHaqiqatan tozalaysizmi?",
    "tozala_tasdiq_xitoy":"🇨🇳 *{ch}* xitoy ostatka: *{n}* ta tovar ({sana}).\nHaqiqatan tozalaysizmi?",
    "tozala_topilmadi":"ℹ️ *{ch}* da tozalaydigan narsa topilmadi.",
    "tozala_ok":     "✅ *{ch}* — tozalandi.",
    "tozala_ha":     "✅ Ha, tozala",
    "tozala_bekor":  "❌ Bekor qilindi.",
    "zakaz_preview": "📋 *Tasdiqlash — {ch}*\n\nJami *{n}* ta tovar:{tafsilot}\n\nTasdiqlaysizmi?",
    "zakaz_tasdiq_btn":"✅ Tasdiqlash",
    "zakaz_bekor_btn":"❌ Bekor qilish",
    "zakaz_bekor_msg":"❌ Zakoz bekor qilindi.",
    "xitoy_qabul_yana":"✅ *{n}* ta tovar qabul qilindi.\n🇨🇳 Jami omborxonada: *{jami}* ta\n\nYana fayl bormi?",
    "xitoy_yana_btn":  "➕ Yana fayl",
    "xitoy_tayyor_btn":"✅ Tayyor — Excel yaratish",
    "kritik_stub":   "📊 Kritik tovarlar ro'yxati tayyorlanmoqda...",
    # Yo'lga konteyner qo'shish
    "b_yolga_kont":    "🚢 Yo'lga konteyner qo'shish",
    "kont_tp_kut":     "📎 *1/2 — Truba/Profil faylini yuboring.*\n\n_(Excel .xlsx format)_",
    "kont_list_kut":   "📎 *2/2 — List faylini yuboring.*\n\n_(Excel .xls/.xlsx format)_",
    "kont_tasdiq_ha":  "✅ Ha, qo'shish",
    "kont_tasdiq_yoq": "❌ Bekor",
    "kont_qoshildi":   "✅ *{n}* ta konteyner yo'lda ro'yxatiga qo'shildi!",
    "kont_xato":       "❌ Fayl o'qishda xato: {xato}",
    "kont_barchasi_bor":"✅ Barcha konteynerlar allaqachon ro'yxatda.",
    # Filyal (user) interfeysi
    "user_main_title":  "📦 *NERJAVEYKA*\n\nNima qilaylik?",
    "b_yolda_excel":    "🚢 Yo'ldagi holat",
    "settings_title_user": "⚙️ *Sozlamalar*",
    "b_boglanish":      "📞 Admin bilan bog'lanish",
    "boglanish_phone":  "📞 Qo'ng'iroq qilish",
    "boglanish_tg":     "💬 Telegramdan bog'lanish",
    "yolda_excel_yoq":  "ℹ️ Hozircha yo'lda konteyner yo'q.",
},
}


def t(lang: str, key: str) -> str:
    """Tarjima olish. Topilmasa — kalitning o'zi qaytadi."""
    return STR.get(lang, STR["cyr"]).get(key, key)
